### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by Andarius68** [MrRar/edit#3]
I just had this in my log file following a server crash and interestingly enough I wasn't using the edit mod for anything at the time. I had used it earlier in the day though. About an hour prior. But at this time I was simply breaking a mossy cobblestone block and using the replacer mod by Sokomine to place some of those onto a recent build.

```
2024-06-03 14:11:42: ERROR[Main]: ServerError: AsyncErr: Lua: Runtime error from mod 'edit' in callback environment_Step(): ...erver/5.9-dev-main/minetest/bin/../mods/edit/preview.lua:284: bad argument #1 to 'pairs' (value expected)
2024-06-03 14:11:42: ERROR[Main]: stack traceback:
2024-06-03 14:11:42: ERROR[Main]: 	[C]: in function 'pairs'
2024-06-03 14:11:42: ERROR[Main]: 	...erver/5.9-dev-main/minetest/bin/../mods/edit/preview.lua:284: in function 'hide_paste_preview'
2024-06-03 14:11:42: ERROR[Main]: 	...erver/5.9-dev-main/minetest/bin/../mods/edit/preview.lua:474: in function 'globalstep'
2024-06-03 14:11:42: ERROR[Main]: 	...n/minetest/bin/../mods/monitoring/builtin/globalstep.lua:73: in function <...n/minetest/bin/../mods/monitoring/builtin/globalstep.lua:55>
2024-06-03 14:11:42: ERROR[Main]: 	...5.9-dev-main/minetest/bin/../builtin/common/register.lua:26: in function <...5.9-dev-main/minetest/bin/../builtin/common/register.lua:12>
```

**Comment by SmallJoker** [comment]
https://github.com/minetest-mods/edit/blob/2eb1728d8beebff43c9f5c164f2cb681405c81b1/preview.lua#L278-L290

`get_children()` may return no value if the entity `d.paste_preview.object` is already gone/removed from the world.

I do yet not know how this mod works, or what it is supposed to to. Leaving it here in case someone would like to fix it. Possible minimalistic fix: (needs testing for visibility side-effects or follow-up errors)
```Lua
for _, objref in pairs(d.paste_preview.object:get_children() or {}) do
```

**Comment by MrRar** [comment]
Apparently I don't have notifications enabled because this is the first time I am seeing this.

I can imagine a scenario where paste_preview would have no children. If they all get unloaded for some reason. For example if the user moves into an unloaded area, any entities attached to the player will get unloaded. I didn't realize get_children() could return nil. How hard would it have been for Luanti to return an empty table instead of nil? I feel like that would have been a lot better. Would prevented a lot of subtle bugs like this.

**Comment by SmallJoker** [comment]
Relevant lua_api.md section: "### Advice on handling `ObjectRefs`": https://github.com/minetest/minetest/blob/5.10.0/doc/lua_api.md?plain=1#L8108

Getters will return `nil` once the entity is gone. This is documented and should be respected by mods. Hence this one might need an update to comply.

**Comment by MrRar** [comment]
Hopefully I will fix it this weekend. Thanks for pointing that out! is_valid() is new. This is my first time seeing it. The documentation has changed. It used to say that there is purposefully no method to test if an object ref is valid or not because saving object refs is unsupported. Everyone ignored that. lol

**Comment by SmallJoker** [comment]
@MrRar `ObjectRef:is_valid()` requires Minetest 5.9.0 or newer. If you'd like to support older versions, I would instead recommend to check against `object:get_pos() == nil`.

**Comment by MrRar** [comment]
> Relevant lua_api.md section: "### Advice on handling `ObjectRefs`": https://github.com/minetest/minetest/blob/5.10.0/doc/lua_api.md?plain=1#L8108
> 
> Getters will return `nil` once the entity is gone. This is documented and should be respected by mods. Hence this one might need an update to comply.

Yeah. I know. I've used get_pos() to check if an ObjectRef is valid in the past.

**Comment by MrRar** [comment]
I reproduced the crash with this code:

```
core.register_chatcommand("doit", {
	func = function(name, param)
		core.clear_objects("quick")
		core.get_player_by_name(name):get_inventory():remove_item("main", ItemStack("edit:paste"))
	end,
})
```

The paste preview needs to be hidden in the same server tick that the object gets cleared.

With the paste block selected and a paste preview shown player types /doit and gets the crash.
